#!/bin/bash

# NOT MEANT TO BE USED CURRENTLY!!
# NEEDS UPDATE SYSTEM
# NEEDS DELETE SYSTEM
# NEEDS UPDATE SYSTEM FOR IMPAMA ITSELF
# NEEDS A CACHING SYSTEM SO IT KNOWS WHATS INSTALLED
# NEEDS A SYSTEM TO INSTALL PACKAGES ONE BY ONE TO PREVENT RACE CONDITIONS
# NEEDS A BETTER SYSTEM TO HANDLE MULTI PACKAGE INSTALL
install_package () {
  SCRIPT_URL="https://raw.githubusercontent.com/SharkPlush/impama/main/install_scripts/$package-install.sh"
  mkdir -p /var/tmp/impama_tmp_install_dir/
  echo "downloading $SCRIPT_URL"
  curl -fsSL "$SCRIPT_URL" -o /var/tmp/impama_tmp_install_dir/
  if ! $SCRIPT_URL; then
  echo "Install script doesn't exist exiting"
  exit 1
  fi
  SCRIPT_PATH="/var/tmp/impama_tmp_install_dir/$package-install.sh"
  chmod +x "$SCRIPT_PATH"
  echo "running installer for $package"
  bash "$SCRIPT_PATH"
  echo "installed $package"
  rm -r /var/tmp/impama_tmp_install_dir/
}

cmd="$1"
shift || true

if [[ "$cmd" == "install" ]]; then
  package="$1"
fi  
  if [[ -z "$package" ]]; then
    echo "Error: No package specified."
    exit 1
  else
    echo "Installing package: $package"
    install_package
  fi
  
if [[ "$cmd" == "help" ]]; then
  echo "impama usage:"
  echo "  impama install <package>  install a package."
  echo "  impama help               shows this help message."
fi
